### ISSUE TITLE
Google colab notebook ?

### ISSUE THREAD

**Issue by timtensor** [Walter0807/MotionBERT#89] opened 2023-08-29 13:52 UTC
Is there a plan to have a google colab note book for the implementation , just to quickly test out inference in the wild ?

**Comment by whatishisname** [comment] 2023-09-13 19:27
duplicate of issue #68

How to do it in Google Colab:
-Download the GitHub repo in colab
-Change directory to motionbert folder
-Upload video & JSON files to colab
-Use !python to run .py files

How to copy the repo to Google Drive from Colab:
-mount your google drive in colab
-On the left side you will see your drive folder
-Drag & drop motionbert folder into the drive folder
-go to your drive and wait & refresh the page

Please use Google search if you don't know how to do any of these steps.

**Comment by Walter0807** [comment] 2023-10-13 05:28
Duplicate of https://github.com/Walter0807/MotionBERT/issues/68

**Closed by Walter0807** 2023-10-13 05:28 UTC
