### ISSUE TITLE
Missing key(s) in state_dict: "temp_embed", "pos_embed",

### ISSUE THREAD

**Issue by Wanglibin14715** [Walter0807/MotionBERT#47] opened 2023-05-22 09:02 UTC
`
Loading checkpoint checkpoint/pose3d/FT_MB_lite_MB_ft_h36m_global_lite/best_epoch.bin
Traceback (most recent call last):
  File "/content/MotionBERT/infer_wild.py", line 45, in <module>
    model_backbone.load_state_dict(checkpoint['model_pos'], strict=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DSTformer:
	Missing key(s) in state_dict: "temp_embed", "pos_embed", ...
        Unexpected key(s) in state_dict: "module.temp_embed", "module.pos_embed", ...
`

I had tried to solve this problem, according to this blog.
https://blog.csdn.net/yangwangnndd/article/details/100207686
however, there are more problems following.

I followed this guide
https://github.com/Walter0807/MotionBERT/blob/main/docs/inference.md
I use this 3dpose model 
https://onedrive.live.com/?authkey=%21ALuKCr9wihi87bI&id=A5438CD242871DF0%21190&cid=A5438CD242871DF0

**Comment by Walter0807** [comment] 2023-05-22 09:24
Duplicate of https://github.com/Walter0807/MotionBERT/issues/24

**Closed by Walter0807** 2023-05-22 09:24 UTC
